### ISSUE TITLE
Smoothing Field with soft constraints

### ISSUE THREAD

**Issue by nicopietroni** [avaxman/libdirectional#53]
Hello,
I noticed the library needs a way to impose soft constraints when smoothing fields (of any type, I am interested in poly vector Field). I think that would be useful in several contexts, for example:

- Suppose you want to derive a field on organic surfaces where you have no sharp features. In that case, one excellent approach is to smooth the principal curvature's direction where the anisotropy of the curvature weights each original direction. 

- Also, to implement something like "Fields on Symmetric Surfaces", I think one should impose target directions with some weight.

Thanks

**Comment by avaxman** [comment]
This was just the topic of the new release 1.8.0.
