### ISSUE TITLE
My mesh can not pass the 501_SeamlessIntegration_bin example 

### ISSUE THREAD

**Issue by lyd405121** [avaxman/libdirectional#57]
- target mesh as below
![bearings](https://user-images.githubusercontent.com/16344694/153705342-6e1749f7-fa8e-4d13-a470-c843440433df.png)

- I run the 301_PowerFields_bin and 303_PolyCurlReduction_bin to create rawfield file: 
- here is the result
[bearings.zip](https://github.com/avaxman/Directional/files/8053113/bearings.zip)
 
- Then I run  501_SeamlessIntegration_bin with  rawfield and  rawfield-cf file
- But I get an error "Solver Failed to factorize!":
![error](https://user-images.githubusercontent.com/16344694/153705491-4a65b33d-a775-4d40-804a-d6d4e947da63.png)

- Render picture as below:
![result](https://user-images.githubusercontent.com/16344694/153705468-1c0876af-bc52-4c37-9411-828dce98404a.png)

- Does I do something wrong to generate the rawfield  file?
- Or just this algorithm can deal with all kinds of mesh?

**Comment by avaxman** [comment]
Hi, I believe your mesh has 7 different connected components, which will create a null space for all operators. The field creation might have failed and is not defined. The geometric issue is that the components are totally independent and thus there are unresolved degrees of freedom. Technically, it's not a problem---you can just work on each of them individually! but you should separate them yourself, Directional does not support it naturally.

**Comment by lyd405121** [comment]
Thanks！I will try it！
