### ISSUE TITLE
Improper function call to power_field?

### ISSUE THREAD

**Issue by kieganlenihan** [avaxman/libdirectional#58]
I followed the tutorial instructions on getting started. When I type `make`, The build fails and gives me the following error:
```Directional/tutorial/103_StreamlineTracing/main.cpp:62:87: error: too few arguments to function call, expected 7, have 6
  directional::power_field(V, F, Eigen::VectorXi(),  Eigen::MatrixXd() , 3, powerField);
  ~~~~~~~~~~~~~~~~~~~~~~~~                                                            ^```
  How do I fix this?

**Comment by avaxman** [comment]
Sorry could you be more specific about the context of this code?

**Comment by kieganlenihan** [comment]
Hi, I'm trying to build the tutorials. So when I type `make`, I get through Tutorial 101 and 102, but when `Building CXX object 103_StreamlineTracing/CMakeFiles/103_StreamlineTracing_bin.dir/main.cpp.o`, the code fails at `Directional/tutorial/103_StreamlineTracing/main.cpp:62:87`. Here is the error I receive: 
```
error: too few arguments to function call, expected 7, have 6
  directional::power_field(V, F, Eigen::VectorXi(),  Eigen::MatrixXd() , 3, powerField);
```
The problem is that `power_field`, defined in `Directional/cmake/../include/directional/power_field.h:35:19:`, has the function signature:
```
IGL_INLINE void power_field(const Eigen::MatrixXd& V,
  const Eigen::MatrixXi& F,
  const Eigen::VectorXi& constFaces,
  const Eigen::MatrixXd& constVectors,
  const Eigen::VectorXd& alignWeights,
  const int N,
  Eigen::MatrixXcd& powerField)
```
Which contains 7 arguments, but the call at the line where the error occurs has 6. So we are missing an argument in the function call. This occurs at four places in the code base:
`Directional/tutorial/103_StreamlineTracing/main.cpp:62`
`Directional/tutorial/105_Sparsity/main.cpp:43`
`Directional/tutorial/202_Sampling/main.cpp:72`
`Directional/tutorial/601_SubdivisionFields/main.cpp:169`

Here are two (seemingly) correct implementations:
`Directional/tutorial/301_PowerFields/main.cpp:34`
`Directional/tutorial/301_PowerFields/main.cpp:35`
I say this because they both have 7 arguments in the call to `directional::power_field`. Am I right here? I don't see an overloaded version of `directional::power_field`, so I assume the function calls with 6 arguments need to be changed?

**Comment by avaxman** [comment]
Thanks for the elaborate feedback! I think I fixed all of them, could you verify it works for you?

**Comment by kieganlenihan** [comment]
Everything built! Thank you
