### ISSUE TITLE
Tutorial 103 loops and throws exception

### ISSUE THREAD

**Issue by afabri** [avaxman/libdirectional#60]
I just git cloned recursively (that is with whatever libigl that clones). 

I compiled with VC 2019 and when I run it, it displays` igl::eigs RESTART` and after a while an exception gets thrown. 
That concerns the same function as mentioned in Issue #16

**Comment by afabri** [comment]
@avaxman does it make sense to try it with the main branch of libigl and Eigen? Will that work or did APIs change?

**Comment by avaxman** [comment]
I have to reintegrate libigl in the new way, since some stuff were broken recently. I will then check this too.

**Comment by avaxman** [comment]
I was able to reproduce. It seems libigl broke something again, and their eigs function doesn't have backward compatiblity <sigh>. I will update to their newest version and check again.

**Comment by avaxman** [comment]
Should be good now---I added one constraint instead of using any eigs. Can you verify?

**Comment by avaxman** [comment]
(Please start from scratch, I totally updated the libigl dependency to their dynamic download version).

**Comment by afabri** [comment]
It works. Thanks.
