### ISSUE TITLE
201_PrincipalMatching Error:Unable to interact with mesh

### ISSUE THREAD

**Issue by whitechopchicken** [avaxman/libdirectional#63]
I can run the 201 example, but I can't pick the triangle on the iglviewer as prompted by the "0+Left button".
To put it more bluntly, the
" viewer.callback_key_down = &key_down.
  viewer.callback_key_up = &key_up.
  viewer.callback_mouse_down = &mouse_down;"
This code does not seem to work.
I have encountered this problem in other examples (e.g., following the prompt key to switch to the viewer). I think it's my fault, but I don't know what to do

**Comment by avaxman** [comment]
hmmm, that is actually just (thinly) wrapped libigl code. Do you in general not getting any UI callbacks from either Directional or libigl tutorials?

**Comment by whitechopchicken** [comment]
Yes. I can only get the code to run and then see the iglviewer and the calculations, but when I go back to keystrokes and mouse input, there is no reflection. This happens in other tutorials examples as well. Thanks for the reply

**Comment by whitechopchicken** [comment]
I tried pressing ctrl additionally to the original button and it worked!
But I still don't understand why. Thank you very much for your reply!
