### ISSUE TITLE
301 Powerfields  When I replace vtb with ftb, I get the error

### ISSUE THREAD

**Issue by whitechopchicken** [avaxman/libdirectional#64]
Hello, I'm trying to get the rawfield of ftb using the 301 method, but when I replaced all vtb with ftb, I encountered the error reported
The problem is in the function update_visualization() as follow:
Assertion failed: fieldList[meshNum]->tb->discTangType()==discTangTypeEnum::VERTEX_SPACES, file E:\Library\Directional\include\directional/directional_viewer.h, line 182

![image](https://github.com/avaxman/Directional/assets/88885300/31207e89-23d1-4df5-b44f-495ae1051d77)

When I comment out ”update_visualization()“, the rawffield written is only two zeros
When I change “viewer.set_selected_vertices(constVertices,1)” in  update_visualization()  to ”viewer.set_selected_vertices(constVertices,2)“, it triggers out of range.

Can anyone tell me how to generate a rawfield for ftb, I'm a beginner

**Comment by whitechopchicken** [comment]
I got it

**Comment by avaxman** [comment]
Sorry, I have not checked issues lately---I trust it's working now?
