### ISSUE TITLE
Generate directional vector field using guide vectors on random points.

### ISSUE THREAD

**Issue by prashant-saxena** [avaxman/libdirectional#66]
Hello,
![image](https://github.com/avaxman/Directional/assets/1583316/12e4c0fe-90c3-4064-ab48-d72c9f051bd7)

1. Blue dots are randomly generated points in UV space. (0-1)
2. Red arrows represent guide vectors. (position and direction)
3. An algorithm that can generate direction on points based on guide vectors (right image)

I gave a try using the K-Nearest-Neighbor algorithm but the resulting vectors are not following guide vectors smoothly.
The resulting data will be mapped on a 3d mesh for custom effects in 3D application Blender. I hope that I have explained 
clearly what I'm looking for. Although I haven't explored "**Directional**" much but looking at the images I think it can 
provide a solution.

Cheers
Prashant

**Comment by avaxman** [comment]
Directional is essentially built on an abstract structure of discrete tangent bundles (so a finite set of vector spaces that you can define a metric connection for). One example is the set of faces to a triangle mesh, but by all means you can derive your own tangent bundle. If you implement all basic operators, you could use the entire of Direcitonal's functionality with your space.

**Comment by avaxman** [comment]
(Happy to discuss this further in the context of your application!)
