### ISSUE TITLE
Remapping intrinsic fields

### ISSUE THREAD

**Issue by hjforsythe-rlp** [avaxman/libdirectional#67]
is there a good method for remapping an intrinsic face-based vector field onto mesh vertices and vice versa? 

the current technique I am using is extracting the ambient 3d coordinates and using the connectivity to average onto faces(or vertices), then reprojecting back into intrinsic frames. 

hoping there is a more direct approach.

**Comment by avaxman** [comment]
There isn't any obvious way to do this. Averaging in (like normals) is a good course of action. Directional will include some default ways to do it in some vague near future.
