### ISSUE TITLE
Quad mesh resolution

### ISSUE THREAD

**Issue by MaxPayneNYPD** [avaxman/libdirectional#68]
Hi! Great work on this cool library!

I have a few question about the usage of the lib though.
The first one is, how to adjust the face number of the output quad mesh, for example, in tutorial 505?
The second one is, how to make the generated quad mesh to align to mesh boundary? Like, for expample, the quad edge in the following screenshot is not aligned with the boundary of the square, is there a way to align it with the boundary?
![mesh](https://github.com/avaxman/Directional/assets/145415942/39d85272-19af-43a5-9bc5-ae39e71d7429)

Thank you!

**Comment by avaxman** [comment]
For the first question, it's a matter of resolution, which you can solve by scaling U and V before meshing.

The second one is not something I currently guarantee... you can use a field the aligns to the boundary, but the integrator will not in general respect that directly (work in progress!).

Amir.
