### ISSUE TITLE
load mesh and extract boundary preserving  quad mesh

### ISSUE THREAD

**Issue by bootsmakes** [avaxman/libdirectional#70]
Hi, I tried the `502_DifferentOrders `and `505_Meshing ` and have couple questions:
1. how to generate the` .rawfield` files from a mesh
2. how to extract the boundary preserving quad mesh from parametrized mesh with uv and save to  `.off`?

**Comment by avaxman** [comment]
1. The raw field is input, but I usually use the tutorial parts from Chapter 3 to create it (as integrable polyvectors).
2. The tutorial itself writes it to OFF. It's not guaranteed to be boundary-preserving though.... this is an upcoming feature!
